name = "box"
main = "src/index.js"
compatibility_date = "2026-06-15"

[vars]
ENABLE_TELEGRAM_BOT = "true"

[[r2_buckets]]
binding = "BUCKET_R2"
bucket_name = "box"

[[kv_namespaces]]
binding = "SHARES_KV"
id = "26c3174fd4ba415e93aa536fe0372680"

[[kv_namespaces]]
binding = "INDEXES_KV"
id = "26c3174fd4ba415e93aa536fe0372680"
